version: "3"

networks:
  default:
    driver: bridge
  npm_proxy:
    name: npm_proxy
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/24

services:
  gui:
    build:
      context: .
      dockerfile: DockerfileGitHub
    container_name: openvpn-ui
    environment:
      - OPENVPN_ADMIN_USERNAME=admin
      - OPENVPN_ADMIN_PASSWORD=admin
      - SITE_NAME=Admin
    ports:
      - "8080:8080/tcp"
      - "1194:1194/udp"
    restart: always
    networks:
      npm_proxy:
        ipv4_address: 172.18.0.10
    devices:
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./example/conf:/etc/openvpn
      - ./example/db:/opt/openvpn-gui/db
